apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./df-cpufunc.yaml
patches:
  - target:
      version: v1
      group: example.com
      kind: DataFlow
    patch: |-
      - op: add
        path: "/spec/userRequirement"
        value: user-requirement
