apiVersion: v1
kind: ConfigMap
metadata:
  name: strategy
  namespace : cpufunc-calcapp
data:
  filterPipeline: |
    - GenerateCombinations
    - TargetResourceFit
    - TargetResourceFitScore
  selectTop : "3"
