apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-ipam-config
  namespace: cpufunc-calcapp
  annotations:
    k8s.v1.cni.cncf.io/resourceName: nvidia.com/mlnx_sriov_netdevice
spec:
  config: '{
    "type": "sriov",
    "cniVersion": "0.3.1",
    "name": "sriov-ipam-config",
    "ipam": {
        "type": "nv-ipam",
        "poolName": "nv-pool1"
      }
    }'
